name: Package Lambda Function

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r lambda/requirements.txt -t lambda/package/

      - name: Package Lambda function
        run: |
          cd lambda/package
          cp ../lambda.py .
          zip -r ../../unity-cs-monitoring-lambda.zip .
      - name: Upload packaged Lambda function
        uses: actions/upload-artifact@v2
        with:
          name: lambda-package
          path: unity-cs-monitoring-lambda.zip
